### ISSUE TITLE
Could you tell me when to append the callback feature?

### ISSUE THREAD

**Issue by owenjeon** [shpongle2634/react-native-kakao-links#10]
안녕하세요. 

현재 To do 상태인 callback 기능이 언제쯤 구현 예정이신지 궁금합니다.

좋은 오픈소스 만들어주셔서 감사합니다. :)

**Comment by shpongle2634** [comment]
안녕하세요! 의견 감사합니다.

콜백을 만들지 못한게, 카카오 링크 api 자체가 딱히 await 하게 동작하지는 않더라고요.
빠르면 이번주 주말쯤? 다시한번 살펴보고 답변 남겨드리겠습니다 : )
