### ISSUE TITLE
package co.jootopia.kakao.link does not exist

### ISSUE THREAD

**Issue by JongGyuChoi** [shpongle2634/react-native-kakao-links#14]
패키지 인스톨하고 링크 후에 빌드하려는데 MainApplication.java 에서 
import co.jootopia.kakao.link.RNKakaoLinkPackage; 를 찾지 못하네요 

그래서  cannot find symbol  new RNKakaoLinkPackage(), 에러도 같이 뜨고 있는 상황입니다..

언링크&언인스톨 후 다시 인스톨 & 링크 하여도 빌드 실패중입니다. 

조언 부탁드려용

**Comment by andpark** [comment]
카카오링크 모듈의 build.gradle 에 
implementation 을
implementation group: 'com.kakao.sdk', name: 'kakaolink', version: '1.15.1'
이렇게 바꿔보세요.
property 파일이 같이 안내려오는것같네요.

프로젝트 폴더에 최상위 build.gradle 에 다음 코드가 들어있는지 확인하시구요.
subprojects {
    repositories {
        mavenCentral()
        maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }
    }
}

그리고, RNKakaoLinkModule.java 파일에 NullSafeReadableMap 클래스가 ReadableMap 의 getEntryIterator 를 구현안하고 있어서, 

@Nonnull
    @Override
    public Iterator<Map.Entry<String, Object>> getEntryIterator() {
      return null;
    }

구현부 추가해주시구요.
