### ISSUE TITLE
buttonObject에 있는 링크가 무조건 앱 설치 팝업이 뜨네요

### ISSUE THREAD

**Issue by samslow** [shpongle2634/react-native-kakao-links#17]
```
const buttonObject = [{
        title: "웹에서 보기",
        link: {
          mobileWebURL: "https://naver.com"
        }
      }]
      const options = {
        objectType: 'feed',//required
        content: contentObject,//required
        social: socialObject,//optional
        buttons: buttonObject//optional
      };
```

이런 식으로 구현 하고 있는데

`mobileWebURL` 이 무조건 앱 설치 링크로 가는데 다른 방법이 있나요 ? (앱이 설치되어있어도 앱 설치 링크로감)

**Comment by samslow** [comment]
`AndroidManifest.xml` 에서 Scheme을 조금 건드렸더니 이제는 앱으로 바로 갑니다.

바로 웹이 뜨게 하고싶은데, 어떻게 해야 할까요 ?

**Comment by shpongle2634** [comment]
답변이 늦었습니다.
문제를 정확히 이해를 못한 상황이라,
mobileWebURL 링크가 네이버 앱이 아닌 네이버 앱 설치가 뜬다는 말씀이신가요?

mobileWebURL이 설정된 경우, 웹 URL로 링크하는 것이  정상이며

일반 버튼의 경우 링크를 보낸 앱이 실행됩니다.
만약 링크를 누르고 SubRoute 등의 실행을 원하신다면 
#11 
이슈를 참조하시길 바랍니다

**Comment by samslow** [comment]
이번에 카카오 디벨로퍼스의 메뉴가 바뀌어서 그런지 저의 경우에는 설정 > 일반 에서 '웹' 플랫폼을 추가 한 뒤 도메인을 등록해 주어야 mobileWebURL로 가더라구요. 

이 부분이 설정되어 있지 않으면 카카오 링크 설명대로 설정 > 일반 에서 'Android'에 설정 되어있는 마켓 링크가 나오더라구요. ㅜㅜ

이 부분 설정하는 내용이 README에 추가되었으면 하는데 어떻게 생각하시나요 ?

**Comment by shpongle2634** [comment]
아! 직접 테스트해보고서야 
무슨 말씀인지 알았습니다 ^^
먼저, 질문사항 정리한번 해보겠습니다.

사용 시나리오는 아래와 같습니다.

1. 앱에서 타유저에게  카카오 링크 전송 
2. 타유저가 링크 클릭
2.1  앱 설치시 앱으로 
2.2 미설치시 마켓 url이 아닌 서비스 홈페이지로

따라서 웰컴페이지를 mobileURL 파라미터에 설정 했으나 앱 설치 페이지로 이동하였고, 
앱이 설치된 경우에도 앱 설치 페이지로 유도된 것 같습니다.

후자의 경우, 앱으로 이동하지 않는 이슈는 scheme를  수정하여  해결하신 것 같습니다.

그 다음으로 전자의 경우 마켓 url로 자꾸 이동하는 문제는
카카오 콘솔 - 내 애플리케이션에서 웹 플랫폼 추가 후 웰컴페이지에 해당하는 도메인을 설정하면 해결가능합니다.

** 웹 URL을 링크하고 싶은 경우 Scrap Template 을 이용하시면 됩니다.

README에 반영하여 수정하도록 하겠습니다.

감사합니다.
