### ISSUE TITLE
KakaoSDK를 찾을 수 없습니다.

### ISSUE THREAD

**Issue by seongjoojin** [shpongle2634/react-native-kakao-links#20]
안녕하세요.

`react-native-kakao-links/ios/RNKakaoLink.m:5:9: fatal error: 'KakaoLink/KakaoLink.h' file not found
#import <KakaoLink/KakaoLink.h>`

위와 같이 오류나서 원인을 찾던 중 KakaoSDK를 설치하지 않은거 같아서 readme.md에 남겨주신 링크로 갔는데 없는 링크로 나와서 어떻게 설치해야할지 모르겠습니다..

일단은 Podfile에 pod 'KakaoOpenSDK'도 추가해봤지만 해결되지 않아서 이슈로 남겨봅니다.

**Comment by shpongle2634** [comment]
안녕하세요
최근에 Kakao Developers  페이지가 리뉴얼됨에 따라, 링크가 유효하지 않았네요.
공식 문서를 읽어보니 카카오 링크가 메시지 API 와 함께 통합된 것 같습니다. 

카카오 SDK 설치는 위 링크에 상세히 설명되어있습니다.
https://developers.kakao.com/docs/latest/ko/message/common

**Comment by seongjoojin** [comment]
감사합니다:)
