### ISSUE TITLE
공유 후 앱으로 보기를 누를 시 오류가 납니다.

### ISSUE THREAD

**Issue by seongjoojin** [shpongle2634/react-native-kakao-links#21]
안녕하세요.

안드로이드에서 해당 라이브러리로
카카오 공유를 카카오톡으로 한 후 앱으로 보기 버튼을 누르면
아래와 같이 오류가 납니다.

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{패키지명/패키지명.KaKaoLinkResponseActivity}: java.lang.ClassNotFoundException: Didn't find class

감사합니다.

**Comment by JuEunSung** [comment]
저도 같은 오류가 나는데요, 혹시 v1 사용하셨나요??

**Comment by JuEunSung** [comment]
오류 해결했습니다 가이드 문서에 있는대로 따라했다가 낭패 봤네요... 
KakaoLinkResponseActivity 이게 아니라 MainActivity에 넣으시면 됩니다.

`<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />

            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data android:scheme="kakao{API_KEY}" android:host="kakaolink" />
        </intent-filter>
      </activity>`

**Comment by seongjoojin** [comment]
감사합니다 덕분에 잘 해결하였습니다:)
