### ISSUE TITLE
apk 설치 후 동작하지않습니다.

### ISSUE THREAD

**Issue by hypark0** [shpongle2634/react-native-kakao-links#28]
안드로이드 애뮬레이터와 컴퓨터에 안드로이드폰 연결해서 
react-native run-android 했을땐 정상 동작합니다.

하지만, gradlew assembleRelease 해서 apk 생성 후, 
폰에 apk 설치해서 실행해보면 동작하지않습니다.

apk 설치했을때 무엇이 달라서 안되는걸까요...ㅜㅜ

**Comment by jhui134** [comment]
apk 생성시에는 사이닝키가 테스트했던키랑 달라지니까 
릴리즈시 사이닝키도 카카오 디벨로퍼에 추가해보세요
