### ISSUE TITLE
Not dismiss Kakao popup after linking

### ISSUE THREAD

**Issue by thaoth58** [shpongle2634/react-native-kakao-links#7]
Hi,
First of all, thank for your module. I have some issues:

1. This response is logged before the popup appears, and I don't know the event when the link is success.
```
const response = await RNKakaoLink.link(options);
console.log(response)
```

2. After linking, the popup is not dismissed.
[https://imgur.com/dY8Hd8O](https://imgur.com/dY8Hd8O)

**Comment by shpongle2634** [comment]
Well, 
I made this Example Using 'async' function.
but Kakao linking doesn't work asynchronous.
So the response doesn't have any infomation about result of kakao linking.  
Don't care about the response of linking. 😥

And you can dismiss with touching 'Cancel' on the top-left.
It's common Usage because IPhone doesn't have Back button.

**Comment by thaoth58** [comment]
This is strange behavior 😥
Like Facebook share, after sharing the popup is dismissed automatically.

I don't know the reason is from the native SDK or not. 
Anyway, thank you so much 👍

**Comment by thaoth58** [comment]
Hi,

Sorry. Could you mind looking at this issue:

When I compile Android:

```
A problem occurred evaluating project ':react-native-kakao-links'.
> Could not get unknown property 'KAKAO_SDK_GROUP' for project ':react-native-kakao-links' of type org.gradle.api.Project.
```

I don't know about Android, but looking into your build.gradle:
`implementation group: project.KAKAO_SDK_GROUP, name: 'kakaolink', version: project.KAKAO_SDK_VERSION`

**Comment by shpongle2634** [comment]
Sorry i'm late.
First, you have to install Kakao SDK following Official guide.
check 'KAKAO_SDK_GROUP' property in your /android gradle settings.
